### ISSUE TITLE
How can I ignore properties of singleton object ?

### ISSUE THREAD

**Issue by sidepelican** [tarunon/XCTAssertNoLeak#11]
Please see this code.

```swift
import XCTAssertNoLeak
import XCTest

class AwesomeObject {}

class SomeStorage {
    static let shared = SomeStorage()
    private let data = AwesomeObject()
}

class SomeDependency {
    let storage: AnyObject = SomeStorage.shared
}

class NoLeaksViewController: UIViewController {
    let dependency = SomeDependency()
    let another = AwesomeObject()
}

extension SomeStorage: CustomTraversable {
    var ignoreAssertion: Bool { true }
}

class ExampleTests: XCTestCase {
    func testExample() throws {
        // failed - 1 object occured memory leak.
        //        - self.dependency.storage.data
        XCTAssertNoLeak(NoLeaksViewController())
    }
}
```

The ViewController has a singleton object through `dependency`, and the ViewController and the singleton has the same type of object.
We can ignore assertion with `CustomTraversable`, but it cannot ignore the children objects.
Even if the singleton's `ignoreAssertion` is `true`, the subtree [lookuped](https://github.com/tarunon/XCTAssertNoLeak/blob/b105cdfa8ee55b17703fff6a653224891420f2e4/Sources/XCTAssertNoLeak/Core/Node.swift#L134) so we have to use `CustomTraversable` for subtree objects too.

In our situation, the singleton and ViewController has the same type of object and it was difficult to identify the objects because of access scope (like extenal library). 

To solve this proble, I think there are three options.
- I have misunderstanding.
- Add another flag to `CustomTraversable` to ignore assertion of subtree objects to .
- Change behavior of `ignoreAssertion`. Ignore subtree.

Give me some advice?

**Comment by tarunon** [comment]
I think `Add another flag to CustomTraversable to ignore assertion of subtree objects to.` is good option. 
If possible, could you please make PR?
