### ISSUE TITLE
Early deallocation

### ISSUE THREAD

**Issue by live-sound** [tarunon/XCTAssertNoLeak#13]
I use this framework for testing viewModels in MVVM paradigm. In some tests viewModel calls several async network requests (which are replaced with stubs in tests) and is deallocated too soon. In these tests context.completion() is not called because nothing holds viewModel and its completion handler is not called too.

Could you add optional timer in `XCTAssertNoLeak` function for such cases?

**Comment by tarunon** [comment]
I'm busy at the moment, and I'm not thinking of formally adding a timer-like feature.
I think you can set the timer by yourself for the one that calls `completion` among the current assert functions.

```swift
XCTAssertNoLeak { context in
  let yourComponent = ...
  context.traverse(yourComponent)
  DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
    context.completion()
  }
} 
```

Any pull-request for functions that generalize this would be appreciated for me.

**Comment by tarunon** [comment]
Hmm, I think you can use `CustomTraversable.intervalForFreeing` feature in that case.
It may work as timer 😃 Please try it 🙏
