### ISSUE TITLE
Build Error(Xcode12.3)

### ISSUE THREAD

**Issue by ericji-o** [tarunon/XCTAssertNoLeak#14]
When I import the framework. I got the following message.
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target.

At the beginning I thought maybe something wrong in my build setting. but when I tried `SnapKit`. the project can be run well.
Could you check for it in the latest Xcode12.3

Thanks

**Comment by tarunon** [comment]
You may trying to import this project into your `APP`, right? But this project is only available for `TEST`. Could you please check that the dependencies are correct?
