### ISSUE TITLE
Warning with Xcode 13 when using with Swift Package Manager

### ISSUE THREAD

**Issue by vincentisambart** [tarunon/XCTAssertNoLeak#16]
[`Package.swift`](https://github.com/tarunon/XCTAssertNoLeak/blob/master/Package.swift) declares the lowest supported iOS version to be iOS 8 (`.iOS(.v8)`), but Xcode 13's minimum iOS version supported is iOS 9. That causes the current warning when using XCTAssertNoLeak via Swift Package Manager:
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99.
```

Could the minimum iOS version be updated to at least iOS 9 (or even 10)?

In a few weeks any submission to the App Store will require Xcode 13, so requiring iOS 9 should not cause any problem (and if someone really need to use an older version of Xcode they could continue to use XCTAssertNoLeak 0.3.1).

**Comment by giginet** [comment]
I suggest bumping up a supported version to iOS 9.0+
