### ISSUE TITLE
False alarm

### ISSUE THREAD

**Issue by live-sound** [tarunon/XCTAssertNoLeak#7]
Hi. 
This lib says that memory leaks occurred in a ViewController, but I see that `deinit` method is called when I push this ViewController in NavigationBar and go back.
So, I guess, this lib shows incorrect results.

**Comment by tarunon** [comment]
Plz let me know the test case code.
Maybe assertion run before deinit 🤔

**Comment by live-sound** [comment]
It's quite simple test:

```
let vm = EmailInputViewModel()
XCTAssertNoLeak(EmailInputViewController(viewModel: vm))
```

Furthermore, XCTAssertNoLeak shows some leaks in my component: 
https://github.com/qiwi/FormattableTextView
```
XCTAssertNoLeak(FormattableTextField())
```
But error message is very strange:
```
failed - 4 object occured memory leak.
- self.formatSymbols[2].value._storage._backing.immutable
- self.formatSymbols[1].value._storage._backing.immutable
- self.inputAttributes[0].value
- self.inputAttributes[0].key._rawValue
```
How those properties may induce memory leaks?
```
public var inputAttributes: [NSAttributedString.Key: Any] = [NSAttributedString.Key.font: UIFont.systemFont(ofSize: 16)]

public var formatSymbols: [Character: CharacterSet] = ["d": CharacterSet.decimalDigits,
														   "w": CharacterSet.letters,
														   "*": CharacterSet(charactersIn: "").inverted]
```

**Comment by tarunon** [comment]
In 1st case, `vm` is captured on out of XCTAssertNoLeak closure, it is capture on test function. 
Please try next one.
```swift
XCTAssertNoLeak(EmailInputViewController(viewModel: EmailInputViewModel()))
```

And 2nd case, I think some of `NS` prefix classes capture or allocated in out of scope.
Sometimes we can see `NS` prefix classes object in buffer of `NSAttributedString.Key`, `CharacterSet` value.

I prepare ignoring way, please try next code on your test cases.
```swift
extension NSString: CustomTraversable {
    public var ignoreAssertion: Bool { return true }
}

extension NSCharacterSet: CustomTraversable {
    public var ignoreAssertion: Bool { return true }
}
```

Please try to this solution. Thanks reporting problems!

**Comment by live-sound** [comment]
Solution for the first case didn't help. But this ViewController uses that component. 

I tried your extensions. Now I have only 1 error message instead of 4 for `FormattableTextField`:
```
failed - 1 object occured memory leak.
- self.inputAttributes[0].value
```

A similar extension for `Any` is needed? Unfortunately, it's not possible to extend `Any` type.

**Comment by live-sound** [comment]
If you're going to add those extensions to the library, add a similar one for `UIColor` too.
With those extensions I only have the problems with `Any`.

**Comment by tarunon** [comment]
Yeah, if `UIColor` also captured, you can write extension of `UIColor`.
`Any` is not class, we can't write extension of `Any`.

**Comment by live-sound** [comment]
So, what can I do with this property?
```
public var inputAttributes: [NSAttributedString.Key: Any]
```

```
failed - 1 object occured memory leak.
- self.inputAttributes[0].value
```

**Comment by live-sound** [comment]
OK, I found solution. You need to write similar extensions for all types which can be set as value in that dictionary with `Any` value.

**Comment by tarunon** [comment]
`UIFont`? I think it's ok to some of UI/NS prefix classes in this lib, that's sure don't make memory leak, make ignore assertion as true in some classes.

**Comment by live-sound** [comment]
- UIFont
- NSAttributedString
- NSParagraphStyle

**Comment by tarunon** [comment]
In this time, Please set these classes extension manually. 🙇 
I have an idea that solve the problem, I will patch them after verification the idea.

**Comment by live-sound** [comment]
Thank you!

**Comment by tarunon** [comment]
@zlib Hi, I try to solve this problem very simple way that ignoring NSCopying default.
Could you please try to branch "ignore_nscopying" on your test case?

**Comment by live-sound** [comment]
Yes, it works.
