### ISSUE TITLE
Test leaks with variable

### ISSUE THREAD

**Issue by live-sound** [tarunon/XCTAssertNoLeak#9]
Right now there is no way to test leaks using a variable. The only option is to use initializer. If you want to call some methods before leaks checking you can't do that. Are there any plans for supporting variables in XCTAssertNoLeak?

**Comment by live-sound** [comment]
You could use a closure where you return your initialized variable like this: https://www.avanderlee.com/swift/memory-leaks-unit-tests/

**Comment by tarunon** [comment]
You can use closure syntax.
https://github.com/tarunon/XCTAssertNoLeak/blob/master/Sources/XCTAssertNoLeak/Front/XCTAssertNoLeak.swift#L12-L29

Is it possible to be solution?

**Comment by live-sound** [comment]
Actually, yes. 
But there is one problem: if you forget to call context.traverse(object), your test will succeed.

**Comment by tarunon** [comment]
Problem...?
I think if someone don't read documentation, I can't save them anymore...😅

or 0 time call traverse make test failuer can save someone?

**Comment by live-sound** [comment]
The problem is this solution https://www.avanderlee.com/swift/memory-leaks-unit-tests/ guarantees that if you don't return a value in the closure your tests won't compile, and there is no such guarantee in your library. It may be critical for a team with junior members. That's why my team doesn't want to use your solution (although it may be more elegant).
If you forget to call `context.completion()` the test will fail. Could you do the same for a case when you forget to call `context.traverse()`?

**Comment by tarunon** [comment]
I improve assert messages when someone don't use `traverse` function. Please check the behavior on master branch.

**Comment by live-sound** [comment]
I tried to write a test without calling context.traverse() and unfortunately the test succeeded.

**Comment by live-sound** [comment]
Now I got it. You didn't make new release with tag. So, in order to use your latest commit I had to use this syntax in cartfile:
`github "tarunon/XCTAssertNoLeak" "master"`

**Comment by tarunon** [comment]
Yeah, I wait you check for new release. Is it good to you now?

**Comment by live-sound** [comment]
Yes, it is good.
